
export const ADD_TO_WANTTOSEE = "ADD_TO_WANTTOSEE"; 
export const REMOVE_FROM_WANTTOSEE = "REMOVE_FROM_WANTTOSEE"; 
export const ADD_TO_SEEN = "ADD_TO_SEEN"; 
export const REMOVE_FROM_SEEN = "REMOVE_FROM_SEEN"; 
export const LOAD_IN_THEATERS = "LOAD_IN_THEATERS"; 
export const LOAD_COMING_SOON = "LOAD_COMING_SOON"; 
export const LOAD_BEST_MOVIES = "LOAD_BEST_MOVIES"; 